language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install coveralls
script:
  - coverage run pelper/pelper.py
  - python -m doctest pelper/pelper.py
after_success:
  - coveralls
